services:
  - type: web
    name: ingestion-api
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /status
    autoDeploy: true
    plan: free 